### ISSUE TITLE
Duplicate Linux when download library.

### ISSUE THREAD

**Issue by lamht** [IronPdf/Iron-Pdf-Documentation#31]
Duplicate Linux when download library.
` ---> (Inner Exception #22) System.AggregateException: One or more errors occurred. (Failed downloading NuGet package at runtime from 'https://www.nuget.org/api/v2/package/IronPdf.Native.Chrome.Linux.Linux/2024.5.11'.  Please add 'IronPdf.Native.Chrome.Linux.Linux version 2024.5.11' Nuget package to your .NET project.) (Failed downloading NuGet package at runtime from 'https://www.nuget.org/api/v2/package/IronPdf.Native.Chrome.Linux.Linux/2024.5.11'.  Please add 'IronPdf.Native.Chrome.Linux.Linux version 2024.5.11' Nuget package to your .NET project.) (Failed downloading NuGet package at runtime from 'https://www.nuget.org/api/v2/package/IronPdf.Native.Chrome.Linux.Linux/2024.5.11'.  Please add 'IronPdf.Native.Chrome.Linux.Linux version 2024.5.11' Nuget package to your .NET project.)
 ---> IronSoftware.Exceptions.IronSoftwareDownloadException: Failed downloading NuGet package at runtime from 'https://www.nuget.org/api/v2/package/IronPdf.Native.Chrome.Linux.Linux/2024.5.11'.  Please add 'IronPdf.Native.Chrome.Linux.Linux version 2024.5.11' Nuget package to your .NET project.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at IronSoftware.Deployment.NuGetDeployment.Download(String url, String path)
   --- End of inner exception stack trace ---
   at IronSoftware.Deployment.NuGetDeployment.Download(String url, String path)
   at IronSoftware.Deployment.NuGetDeployment.Deploy()
   --- End of inner exception stack trace ---
   at IronSoftware.Deployment.NuGetDeployment.Deploy()
   at IronSoftware.Deployment.SmartDeploymentBase.Deploy(Boolean download)
 ---> (Inner Exception #1) IronSoftware.Exceptions.IronSoftwareDownloadException: Failed downloading NuGet package at runtime from 'https://www.nuget.org/api/v2/package/IronPdf.Native.Chrome.Linux.Linux/2024.5.11'.  Please add 'IronPdf.Native.Chrome.Linux.Linux version 2024.5.11' Nuget package to your .NET project.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at IronSoftware.Deployment.NuGetDeployment.Download(String url, String path)
   --- End of inner exception stack trace ---
   at IronSoftware.Deployment.NuGetDeployment.Download(String url, String path)
   at IronSoftware.Deployment.NuGetDeployment.Deploy()<---

 ---> (Inner Exception #2) IronSoftware.Exceptions.IronSoftwareDownloadException: Failed downloading NuGet package at runtime from 'https://www.nuget.org/api/v2/package/IronPdf.Native.Chrome.Linux.Linux/2024.5.11'.  Please add 'IronPdf.Native.Chrome.Linux.Linux version 2024.5.11' Nuget package to your .NET project.
 ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at IronSoftware.Deployment.NuGetDeployment.Download(String url, String path)
   --- End of inner exception stack trace ---
   at IronSoftware.Deployment.NuGetDeployment.Download(String url, String path)
   at IronSoftware.Deployment.NuGetDeployment.Deploy()<---
<---

   --- End of inner exception stack trace ---
   at IronSoftware.Deployment.DeploymentEngine.Deploy[T](String custom_dir, Boolean download)
   at IronPdf.Installation.Initialize()
   at Program.<Main>$(String[] args) in /mnt/d/flex/flex-post/src/Flex.PostService/Program.cs:line 192
root@LPP00251942D:/mnt/d/flex/flex-post/src/Flex.PostService# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@LPP00251942D:/mnt/d/flex/flex-post/src/Flex.PostService#`

**Comment by schirane1** [comment]
How was this resolved @lamht ?
